# Generated by Django 3.0.8 on 2020-11-18 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0003_auto_20201118_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='topics',
        ),
        migrations.AddField(
            model_name='topic',
            name='book',
            field=models.ForeignKey(db_column='bookId', default=1, on_delete=django.db.models.deletion.CASCADE, to='customer_app.Book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
