# Generated by Django 3.0.8 on 2020-11-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0004_auto_20201118_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
