# Generated by Django 3.0.8 on 2020-11-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0005_auto_20201118_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTime',
            field=models.DateTimeField(null=True),
        ),
    ]
