# Generated by Django 3.0.8 on 2020-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0006_auto_20201118_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='option',
            field=models.CharField(choices=[('buy', 'mua sách truyền thống'), ('eBuy', 'mua sách điện tử'), ('eRent', 'thuê sách điện tử')], default='buy', max_length=10),
        ),
    ]
