# Generated by Django 3.0.8 on 2020-11-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0007_auto_20201118_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='book',
            field=models.ForeignKey(db_column='bookISBN', on_delete=django.db.models.deletion.CASCADE, to='customer_app.Book'),
        ),
    ]
