# Generated by Django 3.0.8 on 2020-11-19 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0008_auto_20201118_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronic',
            old_name='rent_duration',
            new_name='rentDuration',
        ),
        migrations.RenameField(
            model_name='electronic',
            old_name='rent_price',
            new_name='rentPrice',
        ),
        migrations.RenameField(
            model_name='traditional',
            old_name='allow_number',
            new_name='allowNumber',
        ),
        migrations.AlterField(
            model_name='electronic',
            name='book',
            field=models.OneToOneField(db_column='bookISBN', on_delete=django.db.models.deletion.CASCADE, to='customer_app.Book'),
        ),
        migrations.AlterField(
            model_name='traditional',
            name='book',
            field=models.OneToOneField(db_column='bookISBN', on_delete=django.db.models.deletion.CASCADE, to='customer_app.Book'),
        ),
    ]
