# Generated by Django 3.0.8 on 2020-11-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0009_auto_20201119_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='export',
            old_name='export_time',
            new_name='exportTime',
        ),
        migrations.RenameField(
            model_name='import',
            old_name='import_time',
            new_name='importTime',
        ),
        migrations.AlterUniqueTogether(
            name='export',
            unique_together={('book', 'storage', 'exportTime')},
        ),
        migrations.AlterUniqueTogether(
            name='import',
            unique_together={('book', 'storage', 'importTime')},
        ),
    ]
