# Generated by Django 3.0.8 on 2020-11-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0010_auto_20201119_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='traditional',
            name='id',
        ),
        migrations.AlterField(
            model_name='electronic',
            name='book',
            field=models.OneToOneField(db_column='ISBN', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customer_app.Book'),
        ),
        migrations.AlterField(
            model_name='traditional',
            name='book',
            field=models.OneToOneField(db_column='ISBN', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customer_app.Book'),
        ),
    ]
