# Generated by Django 3.0.8 on 2020-11-20 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0010_auto_20201119_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic',
            name='book',
            field=models.OneToOneField(db_column='ISBN', on_delete=django.db.models.deletion.CASCADE, to='customer_app.Book'),
        ),
        migrations.AlterField(
            model_name='export',
            name='book',
            field=models.ForeignKey(db_column='bookISBN', on_delete=django.db.models.deletion.CASCADE, to='customer_app.Traditional'),
        ),
        migrations.AlterField(
            model_name='import',
            name='book',
            field=models.ForeignKey(db_column='bookISBN', on_delete=django.db.models.deletion.CASCADE, to='customer_app.Traditional'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='book',
            field=models.ForeignKey(db_column='bookISBN', on_delete=django.db.models.deletion.CASCADE, to='customer_app.Traditional'),
        ),
        migrations.AlterField(
            model_name='traditional',
            name='book',
            field=models.OneToOneField(db_column='ISBN', on_delete=django.db.models.deletion.CASCADE, to='customer_app.Book'),
        ),
    ]
