# Generated by Django 3.0.8 on 2020-11-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0011_auto_20201120_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='book',
            field=models.ForeignKey(db_column='bookISBN', on_delete=django.db.models.deletion.CASCADE, to='customer_app.Traditional'),
        ),
        migrations.AlterField(
            model_name='import',
            name='book',
            field=models.ForeignKey(db_column='bookISBN', on_delete=django.db.models.deletion.CASCADE, to='customer_app.Traditional'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='book',
            field=models.ForeignKey(db_column='bookISBN', on_delete=django.db.models.deletion.CASCADE, to='customer_app.Traditional'),
        ),
    ]
