# Generated by Django 3.0.8 on 2020-11-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0012_auto_20201120_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(db_column='customerId', on_delete=django.db.models.deletion.CASCADE, to='customer_app.Customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(db_column='customerId', on_delete=django.db.models.deletion.CASCADE, to='customer_app.Customer'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='storage',
            field=models.ForeignKey(db_column='storageId', on_delete=django.db.models.deletion.PROTECT, to='customer_app.Storage'),
        ),
    ]
