# Generated by Django 3.0.8 on 2020-11-22 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0015_auto_20201122_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='staff',
            field=models.ForeignKey(db_column='staffId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_app.Staff'),
        ),
        migrations.AddField(
            model_name='import',
            name='staff',
            field=models.ForeignKey(db_column='staffId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_app.Staff'),
        ),
    ]
