# Generated by Django 3.0.8 on 2020-11-22 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0016_auto_20201122_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='staff',
            field=models.ForeignKey(db_column='staffId', on_delete=django.db.models.deletion.PROTECT, to='customer_app.Staff'),
        ),
        migrations.AlterField(
            model_name='import',
            name='staff',
            field=models.ForeignKey(db_column='staffId', on_delete=django.db.models.deletion.PROTECT, to='customer_app.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='export',
            unique_together={('book', 'storage', 'staff', 'exportTime')},
        ),
        migrations.AlterUniqueTogether(
            name='import',
            unique_together={('book', 'storage', 'staff', 'importTime')},
        ),
    ]
