version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_USER: root
      MYSQL_PASSWORD: Admin.12345
      MYSQL_ROOT_PASSWORD: admin
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db